name: fishsim
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - pickle5
  - scipy
  - scikit-image
  - click
  - pyyaml
  - black
  - pytest
  - pathlib
  - seaborn
  - python-opencv
  - scikit-learn
